/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as QuizLayoutImport } from './routes/_quizLayout'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutAuthImport } from './routes/_layout/_auth'
import { Route as QuizLayoutUsernameQuizSlugIndexImport } from './routes/_quizLayout/$username/$quizSlug/index'
import { Route as QuizLayoutUsernameQuizSlugFlashcardsImport } from './routes/_quizLayout/$username/$quizSlug/flashcards'

// Create Virtual Routes

const LayoutIndexLazyImport = createFileRoute('/_layout/')()
const QuizLayoutTestLazyImport = createFileRoute('/_quizLayout/test')()
const LayoutVerifiedLazyImport = createFileRoute('/_layout/verified')()
const LayoutSignupLazyImport = createFileRoute('/_layout/signup')()
const LayoutSigninLazyImport = createFileRoute('/_layout/signin')()
const LayoutQuizSearchLazyImport = createFileRoute('/_layout/quiz-search')()
const LayoutPasswordResetLazyImport = createFileRoute(
  '/_layout/password-reset',
)()
const LayoutForgotPasswordLazyImport = createFileRoute(
  '/_layout/forgot-password',
)()
const LayoutVerificationTokenLazyImport = createFileRoute(
  '/_layout/verification/$token',
)()
const LayoutAuthUsernameLazyImport = createFileRoute(
  '/_layout/_auth/$username',
)()

// Create/Update Routes

const QuizLayoutRoute = QuizLayoutImport.update({
  id: '/_quizLayout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexLazyRoute = LayoutIndexLazyImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() => import('./routes/_layout/index.lazy').then((d) => d.Route))

const QuizLayoutTestLazyRoute = QuizLayoutTestLazyImport.update({
  path: '/test',
  getParentRoute: () => QuizLayoutRoute,
} as any).lazy(() =>
  import('./routes/_quizLayout/test.lazy').then((d) => d.Route),
)

const LayoutVerifiedLazyRoute = LayoutVerifiedLazyImport.update({
  path: '/verified',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/verified.lazy').then((d) => d.Route),
)

const LayoutSignupLazyRoute = LayoutSignupLazyImport.update({
  path: '/signup',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/signup.lazy').then((d) => d.Route),
)

const LayoutSigninLazyRoute = LayoutSigninLazyImport.update({
  path: '/signin',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/signin.lazy').then((d) => d.Route),
)

const LayoutQuizSearchLazyRoute = LayoutQuizSearchLazyImport.update({
  path: '/quiz-search',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/quiz-search.lazy').then((d) => d.Route),
)

const LayoutPasswordResetLazyRoute = LayoutPasswordResetLazyImport.update({
  path: '/password-reset',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/password-reset.lazy').then((d) => d.Route),
)

const LayoutForgotPasswordLazyRoute = LayoutForgotPasswordLazyImport.update({
  path: '/forgot-password',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/forgot-password.lazy').then((d) => d.Route),
)

const LayoutAuthRoute = LayoutAuthImport.update({
  id: '/_auth',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutVerificationTokenLazyRoute =
  LayoutVerificationTokenLazyImport.update({
    path: '/verification/$token',
    getParentRoute: () => LayoutRoute,
  } as any).lazy(() =>
    import('./routes/_layout/verification.$token.lazy').then((d) => d.Route),
  )

const LayoutAuthUsernameLazyRoute = LayoutAuthUsernameLazyImport.update({
  path: '/$username',
  getParentRoute: () => LayoutAuthRoute,
} as any).lazy(() =>
  import('./routes/_layout/_auth/$username.lazy').then((d) => d.Route),
)

const QuizLayoutUsernameQuizSlugIndexRoute =
  QuizLayoutUsernameQuizSlugIndexImport.update({
    path: '/$username/$quizSlug/',
    getParentRoute: () => QuizLayoutRoute,
  } as any)

const QuizLayoutUsernameQuizSlugFlashcardsRoute =
  QuizLayoutUsernameQuizSlugFlashcardsImport.update({
    path: '/$username/$quizSlug/flashcards',
    getParentRoute: () => QuizLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_quizLayout': {
      preLoaderRoute: typeof QuizLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/_auth': {
      preLoaderRoute: typeof LayoutAuthImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/forgot-password': {
      preLoaderRoute: typeof LayoutForgotPasswordLazyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/password-reset': {
      preLoaderRoute: typeof LayoutPasswordResetLazyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/quiz-search': {
      preLoaderRoute: typeof LayoutQuizSearchLazyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/signin': {
      preLoaderRoute: typeof LayoutSigninLazyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/signup': {
      preLoaderRoute: typeof LayoutSignupLazyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/verified': {
      preLoaderRoute: typeof LayoutVerifiedLazyImport
      parentRoute: typeof LayoutImport
    }
    '/_quizLayout/test': {
      preLoaderRoute: typeof QuizLayoutTestLazyImport
      parentRoute: typeof QuizLayoutImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexLazyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/_auth/$username': {
      preLoaderRoute: typeof LayoutAuthUsernameLazyImport
      parentRoute: typeof LayoutAuthImport
    }
    '/_layout/verification/$token': {
      preLoaderRoute: typeof LayoutVerificationTokenLazyImport
      parentRoute: typeof LayoutImport
    }
    '/_quizLayout/$username/$quizSlug/flashcards': {
      preLoaderRoute: typeof QuizLayoutUsernameQuizSlugFlashcardsImport
      parentRoute: typeof QuizLayoutImport
    }
    '/_quizLayout/$username/$quizSlug/': {
      preLoaderRoute: typeof QuizLayoutUsernameQuizSlugIndexImport
      parentRoute: typeof QuizLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutAuthRoute.addChildren([LayoutAuthUsernameLazyRoute]),
    LayoutForgotPasswordLazyRoute,
    LayoutPasswordResetLazyRoute,
    LayoutQuizSearchLazyRoute,
    LayoutSigninLazyRoute,
    LayoutSignupLazyRoute,
    LayoutVerifiedLazyRoute,
    LayoutIndexLazyRoute,
    LayoutVerificationTokenLazyRoute,
  ]),
  QuizLayoutRoute.addChildren([
    QuizLayoutTestLazyRoute,
    QuizLayoutUsernameQuizSlugFlashcardsRoute,
    QuizLayoutUsernameQuizSlugIndexRoute,
  ]),
])

/* prettier-ignore-end */
