name: Publish to GitHub Container Registry

on:
  workflow_dispatch:
  push:
    branches:
      - main
  
jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build the Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/quizer-web:latest .

      - name: Push the container image
        run: docker push ghcr.io/${{ github.repository_owner }}/quizer-web:latest